name: CI Pipeline

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main
  pull_request:
    branches:
      - main  # Запуск при создании pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker image with .NET Core SDK 3.1
        run: |
          docker pull mcr.microsoft.com/dotnet/core/sdk:3.1  # Загружаем образ .NET Core 3.1

      - name: Restore dependencies using Docker container
        run: |
          docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet restore

      - name: Build project using Docker container
        run: |
          docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet build --configuration Release

      - name: Run tests using Docker container
        run: |
          docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet test --no-build
